

import React, { useState, useEffect } from 'react';
import { BookOpenIcon, GlobeIcon, LightbulbIcon } from './icons';

interface AboutModalProps {
  onClose: () => void;
}

// FIX: Specify that the icon element can accept a className prop.
const ModalSection: React.FC<{ title: string; icon: React.ReactElement<{ className?: string }>; children: React.ReactNode }> = ({ title, icon, children }) => (
  <div>
    <h3 className="flex items-center gap-3 font-serif text-2xl text-brown-dark mb-3">
      {React.cloneElement(icon, { className: 'h-6 w-6 text-gold' })}
      <span>{title}</span>
    </h3>
    <div className="space-y-3 text-secondary-text pl-9">
        {children}
    </div>
  </div>
);


export const AboutModal: React.FC<AboutModalProps> = ({ onClose }) => {
  const [isShowing, setIsShowing] = useState(false);

  useEffect(() => {
    const timer = setTimeout(() => setIsShowing(true), 10);
    document.body.style.overflow = 'hidden';
    return () => {
      clearTimeout(timer);
      document.body.style.overflow = 'auto';
    }
  }, []);

  const handleBackdropClick = (e: React.MouseEvent<HTMLDivElement>) => {
    if (e.target === e.currentTarget) {
      closeModal();
    }
  };

  const closeModal = () => {
    setIsShowing(false);
    setTimeout(onClose, 300); // Wait for animation to finish
  }

  return (
    <div
      className={`fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4 transition-opacity duration-300 ease-in-out ${isShowing ? 'opacity-100' : 'opacity-0'}`}
      onClick={handleBackdropClick}
      aria-modal="true"
      role="dialog"
    >
      <div
        className={`bg-surface rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-hidden flex flex-col transition-all duration-300 ease-in-out ${isShowing ? 'opacity-100 scale-100' : 'opacity-0 scale-95'}`}
        onClick={e => e.stopPropagation()}
      >
        <div className="p-6 md:p-8 flex-grow overflow-y-auto relative">
           <button 
            onClick={closeModal} 
            className="absolute top-4 right-4 bg-cream rounded-full p-2 text-brown-dark hover:bg-brown/10 focus:outline-none focus:ring-2 focus:ring-gold"
            aria-label="Close modal"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
          </button>
          
          <div className="text-center mb-8">
            <h2 className="font-serif text-4xl text-brown-dark">About BrewMuse</h2>
            <p className="text-secondary-text mt-1">Your personal AI coffee sommelier.</p>
          </div>
          
          <div className="space-y-8">
            <p className="text-center text-brown-dark bg-cream p-4 rounded-lg border border-subtle-border">
              <strong>BrewMuse</strong> is an exploration into the world of coffee, powered by generative AI. Our mission is to help you discover new trends, create unique recipes, and find the perfect cup for any moment.
            </p>

            <ModalSection title="The Magic of AI" icon={<LightbulbIcon />}>
              <p>The recipes, flavor profiles, origin stories, and brewing tips you see are crafted by Google's powerful AI. It analyzes patterns from vast amounts of text to generate creative and inspiring coffee ideas.</p>
              <p>The beautiful images are also generated by AI, designed to bring the recipes to life. While we strive for delicious and accurate suggestions, always use your best judgment when preparing food and drink.</p>
            </ModalSection>
            
            <ModalSection title="Sources & Attribution" icon={<GlobeIcon />}>
                <p>To find the latest trends, BrewMuse uses Google Search to research what's popular on blogs and social media. When we use this feature, we provide a "Sources & Inspiration" section in the recipe details. We encourage you to visit these links to see the original content and support the creators who inspire us.</p>
            </ModalSection>

             <ModalSection title="Happy Brewing!" icon={<BookOpenIcon />}>
                <p>Thank you for joining us on this coffee journey. We hope BrewMuse inspires you to experiment, learn, and enjoy the rich, wonderful world of coffee.</p>
            </ModalSection>
          </div>
        </div>
      </div>
    </div>
  );
};